#include <nmosh/plugin-if.h>
#include <wx/wx.h>
#include <wx/textctrl.h>

extern "C" {
// }

MOSHEXPORT
void*
mwx_textattr_create(void){
    return new wxTextAttr();
}

MOSHEXPORT
void
mwx_textattr_destroy(wxTextAttr* ta){
    delete ta;
}

MOSHEXPORT
void
mwx_textattr_merge(wxTextAttr* ta, wxTextAttr* op){
    ta->Merge(*op);
}

MOSHEXPORT
void
mwx_textattr_setsize_pixel(wxTextAttr* ta, int size){
    ta->SetFontPixelSize(size);
}

MOSHEXPORT
void
mwx_textattr_setsize_point(wxTextAttr* ta, int size){
    ta->SetFontSize(size);
}

MOSHEXPORT
void
mwx_textattr_setfamily(wxTextAttr* ta, int family){
    ta->SetFontFamily((wxFontFamily)family);
}

NMOSH_CONSTANT_BEGIN(mwx_textattr)
    /* FIXME: Set* will set them automagically */
    NMOSH_EXPORT_SYMBOL_INT(wxTEXT_ATTR_TEXT_COLOUR)
    NMOSH_EXPORT_SYMBOL_INT(wxTEXT_ATTR_BACKGROUND_COLOUR)
    NMOSH_EXPORT_SYMBOL_INT(wxTEXT_ATTR_FONT_FACE)
    NMOSH_EXPORT_SYMBOL_INT(wxTEXT_ATTR_FONT_POINT_SIZE)
    NMOSH_EXPORT_SYMBOL_INT(wxTEXT_ATTR_FONT_PIXEL_SIZE)
    NMOSH_EXPORT_SYMBOL_INT(wxTEXT_ATTR_FONT_WEIGHT)
    NMOSH_EXPORT_SYMBOL_INT(wxTEXT_ATTR_FONT_ITALIC)
    NMOSH_EXPORT_SYMBOL_INT(wxTEXT_ATTR_FONT_UNDERLINE)
    NMOSH_EXPORT_SYMBOL_INT(wxTEXT_ATTR_FONT_STRIKETHROUGH)
    NMOSH_EXPORT_SYMBOL_INT(wxTEXT_ATTR_FONT_ENCODING)
    NMOSH_EXPORT_SYMBOL_INT(wxTEXT_ATTR_FONT_FAMILY)
    NMOSH_EXPORT_SYMBOL_INT(wxTEXT_ATTR_FONT_SIZE)
    NMOSH_EXPORT_SYMBOL_INT(wxTEXT_ATTR_FONT)
    /* Font families */
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFAMILY_DEFAULT)
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFAMILY_DECORATIVE)
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFAMILY_ROMAN)
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFAMILY_SCRIPT)
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFAMILY_SWISS)
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFAMILY_MODERN)
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFAMILY_TELETYPE)
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFAMILY_UNKNOWN)
    /* Font flags */
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFLAG_DEFAULT)
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFLAG_ITALIC)
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFLAG_SLANT)
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFLAG_LIGHT)
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFLAG_BOLD)
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFLAG_ANTIALIASED)
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFLAG_NOT_ANTIALIASED)
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFLAG_UNDERLINED)
    NMOSH_EXPORT_SYMBOL_INT(wxFONTFLAG_STRIKETHROUGH)
NMOSH_CONSTANT_END()

// {
}
