(mosh-wx-aui
  c-function-table
  *internal*
  (plugin: mosh_wx)
  (libname: mosh_wx aui)
  (parent-libname: mosh_wx)
  (c-import: "mwx_aui.cpp" "mwx_auinotebook.cpp")
  #(ret name args)
  (void* mwx_aui_create (void* int))
  (void* mwx_aui_paneinfo_create)
  (void mwx_aui_paneinfo_destroy (void*))
  (int mwx_aui_add (void* void* void*))
  (void mwx_aui_update (void*))
  (void* mwx_aui_notebook_create (void* int int))
  (int mwx_aui_notebook_addpage (void* void* void*))
  (void mwx_aui_notebook_deletepage (void* int))
  (void mwx_aui_notebook_removepage (void* int))
  (void mwx_aui_notebook_setselection (void* int))
  (void mwx_aui_notebook_getpageindex (void* void*))
  (void mwx_aui_notebook_setpagetext (void* int void*))

  (void mwx_aui_paneinfo_bestsize (void* int int))
  (void mwx_aui_paneinfo_bottomdockable (void* int))
  (void mwx_aui_paneinfo_caption (void* void*))
  (void mwx_aui_paneinfo_caption_visible (void* int))
  (void mwx_aui_paneinfo_centrepane (void*))
  (void mwx_aui_paneinfo_closebutton (void* int))
  (void mwx_aui_paneinfo_defaultpane (void*))
  (void mwx_aui_paneinfo_destroyonclose (void* int))
  (void mwx_aui_paneinfo_direction (void* int))
  (void mwx_aui_paneinfo_dock (void*))
  (void mwx_aui_paneinfo_dockfixed (void* int))
  (void mwx_aui_paneinfo_dockable (void* int))
  (void mwx_aui_paneinfo_fixed (void*))
  (void mwx_aui_paneinfo_float (void*))
  (void mwx_aui_paneinfo_floatable (void* int))
  (void mwx_aui_paneinfo_floatingposition (void* int int))
  (void mwx_aui_paneinfo_floatingsize (void* int int))
  (void mwx_aui_paneinfo_leftdockable (void* int))
  (void mwx_aui_paneinfo_maxsize (void* int int))
  (void mwx_aui_paneinfo_maximizebutton (void* int))
  (void mwx_aui_paneinfo_minsize (void* int int))
  (void mwx_aui_paneinfo_minimizebutton (void* int))
  (void mwx_aui_paneinfo_movable (void* int))
  (void mwx_aui_paneinfo_pinbutton (void* int))
  (void mwx_aui_paneinfo_rightdockable (void* int))
  (void mwx_aui_paneinfo_show (void* int))
  (void mwx_aui_paneinfo_toolbarpane (void*))
  (void mwx_aui_paneinfo_topdockable (void* int))
  )
